import { Inter } from "next/font/google";
import Index from "@/app/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin pay App",
  description: "Generated by AbaSayo Company",
};

export default function PrincipalLayout({ children }) {
  return <Index>{children}</Index>;
}
